# Ref: https://cloud.google.com/appengine/docs/flexible/nodejs/configuring-your-app-with-app-yaml
runtime: go
env: flex
api_version: 1

env_variables:
  OAUTH2_CALLBACK: https://rjj-work-testing.appspot.com/oauth2callback

# [START cloudsql_settings]
# Replace INSTANCE_CONNECTION_NAME with the value obtained when configuring your
# Cloud SQL instance, available from the Google Cloud Console or from the Cloud SDK.
# For SQL v2 instances, this should be in the form of "project:region:instance".
# Cloud SQL v1 instances are not supported.
#
# This should match the value in config.go
beta_settings:
  cloud_sql_instances: rjj-work-testing:us-east1:rjj-work-mysql-01
# [END cloudsql_settings]

# Changes by rjj
#automatic_scaling:
#	min_num_instances: 1
#	max_num_instances: 2
manual_scaling:
  instances: 1
